import { holidayInn1, holidayInn2, holidayInn3, holidayInn4, warehouseGym1, warehouseGym2, warehouseGym3, warehouseGym4, warehouseGym5, foretCafe1, foretCafe2, foretCafe3, foretCafe4, foretCafe5, foretCafe6, foretCafe7, bikanerwala1, bikanerwala2, bikanerwala3, bikanerwala4, bikanerwala5, bikanerwala6, bikanerwala7, bikanerwala8, commongrounds1, commongrounds2, commongrounds3, commongrounds4, commongrounds6, commongrounds7, commongrounds8, warehouseGymJumeirahPark1, warehouseGymJumeirahPark2, warehouseGymJumeirahPark3, warehouseGymJumeirahPark4, warehouseGymJumeirahPark5, warehouseGymDIFC1, warehouseGymDIFC2, warehouseGymDIFC3, warehouseGymDIFC4, warehouseGymDIFC5, warehouseGymDIFC6, warehouseGymDIFC7, warehouseGymKhawaneej1, warehouseGymKhawaneej2, warehouseGymKhawaneej3, warehouseGymKhawaneej4, warehouseGymKhawaneej5, warehouseGymYasBay1, warehouseGymYasBay2, warehouseGymYasBay3, warehouseGymYasBay4, warehouseGymYasBay5, warehouseGymYasBay6, warehouseGymYasBay7, warehouseGymYasBay8, warehouseGymYasBay9, warehouseGymYasBay10, warehouseGymYasBay11, warehouseGymYasBay12, warehouseGymYasBay13, watchAvenue1, watchAvenue2, watchAvenue3, watchAvenue4, watchAvenue5, watchAvenue6, duKiosk1, duKiosk2, duKiosk3, alSalamTower1, alSalamTower2, alSalamTower3, octagonOffice1, octagonOffice2, octagonOffice3, flor2, flor3, flor4, flor6, flor7, flor8, flor9, flor10, flor11, flor12, flor13, flor15, flor16, flor17, flor19, flor20, flor22, flor23, haldirams4, haldirams5, haldirams6, haldirams7, haldirams8, haldirams9, haldirams10, haldirams11, haldirams12, londonSkin2, londonSkin3, londonSkin4, londonSkin5, londonSkin7, londonSkin8, londonSkin9, londonSkin10, zaraMarina1, zaraMarina2, zaraMarina3, zaraMarina4, zaraMarina5, warehouseGymBizBay1, warehouseGymBizBay2, warehouseGymBizBay3, warehouseGymBizBay4, warehouseGymBizBay5, warehouseGymBizBay6, warehouseGymBizBay7, warehouseGymSpringsSouk1, warehouseGymSpringsSouk2, warehouseGymSpringsSouk3, warehouseGymSpringsSouk4, warehouseGymSpringsSouk5, goldenGoose1, goldenGoose2, goldenGoose3, goldenGoose4, goldenGoose5, amano1, amano2, amano3, octagonOffice4, octagonOffice5, trouvaille1, trouvaille2, trouvaille3, trouvaille4, trouvaille5, natureland1, natureland2, natureland3, equitiesFirst1, equitiesFirst2, equitiesFirst3, equitiesFirst4, barakaOffice1, barakaOffice2, barakaOffice3, barakaOffice4, barakaOffice5, barakaOffice6, barakaOffice7, barakaOffice8, barakaOffice9, barakaOffice10, barakaOffice11, warehouseGymDSP1, warehouseGymDSP2, warehouseGymDSP3, warehouseGymDSP4, warehouseGymDSP5, londonSkin1, tbk1, tbk2, tbk3, tbk4, tbk5, tbk6, tbk7, tbk8, tbk9 } from "@/assets/generated/images";

import type { ImageSet } from "@/assets/generated/images";

export interface Project {
  slug: string;
  name: string;
  sector: string;
  location: string;
  client: string;
  scope: string;
  year: string;
  image: ImageSet;
  gallery: ImageSet[];
  summary: string;
  narrative: string[];
}

export const projects: Project[] = [
  {
    slug: "holiday-inn-al-barsha",
    name: "Holiday Inn — Al Barsha",
    sector: "Hospitality",
    location: "Al Barsha, Dubai",
    client: "Holiday Inn",
    scope: "Fit-out & MEP Works",
    year: "2026",
    image: holidayInn1,
    gallery: [holidayInn2, holidayInn3, holidayInn4],
    summary:
      "A full hotel renovation across all rooms and floors, delivering a cohesive upgrade in finishes, systems and guest experience.",
    narrative: [
      "The renovation scope covered a full interior upgrade across all guest rooms, corridors and public areas, with a consistent design language applied across every floor.",
      "We coordinated a complete refresh of finishes, joinery, lighting and MEP services to improve durability, guest comfort and operational efficiency without compromising the hotel's existing structure.",
      "The works included room-by-room refurbishment, upgraded FF&E, revised circulation planning and technical integration to deliver a cohesive, modern hospitality environment at scale.",
    ],
  },
  {
    slug: "warehouse-gym-ibn-battuta",
    name: "Warehouse Gym — Ibn Battuta",
    sector: "Fitness",
    location: "Ibn Battuta Mall, Dubai",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out, Joinery & MEP Works",
    year: "2022",
    image: warehouseGym1,
    gallery: [warehouseGym2, warehouseGym3, warehouseGym4, warehouseGym5],
    summary:
      "A raw, industrial temple to strength — polished concrete, exposed services and warm timber, tuned for performance.",
    narrative: [
      "The brief was to translate Warehouse Gym's DNA — grit, honesty, and precision — into a mall footprint without softening a single edge.",
      "We opened the ceiling, blacked out the services and let acoustic baffles carry the rhythm of the space. Every duct run was coordinated to double as visual language.",
      "Full MEP design and execution was delivered in-house, from load calculations to smart lighting scenes that shift with the training programme.",
    ],
  },
  {
    slug: "foret-cafe",
    name: "Forêt Café",
    sector: "Restaurants",
    location: "Downtown Dubai",
    client: "Forêt Hospitality",
    scope: "Design, Fit-out & Joinery",
    year: "2023",
    image: foretCafe1,
    gallery: [foretCafe2, foretCafe3, foretCafe4, foretCafe5, foretCafe6, foretCafe7],
    summary:
      "A Parisian-inspired garden café where a solid emerald marble bar anchors a living wall of greenery.",
    narrative: [
      "Every element — from the hand-tufted banquettes to the aged brass pendants — was joinery-crafted at our Al Quoz workshop.",
      "The signature emerald marble was sourced as a single slab, book-matched, then wet-polished on site to preserve the veining.",
      "MEP was engineered for silence: the plant is invisible, the acoustics are cinema-grade, and the guest hears only conversation.",
    ],
  },
  {
    slug: "bikanerwala",
    name: "Bikanerwala",
    sector: "Retail & Restaurants",
    location: "Sheikh Zayed Road",
    client: "Bikanerwala Foods",
    scope: "Turnkey Fit-out & MEP",
    year: "2022",
    image: bikanerwala1,
    gallery: [bikanerwala2, bikanerwala3, bikanerwala4, bikanerwala5, bikanerwala6, bikanerwala7, bikanerwala8],
    summary:
      "A jewel-box sweet shop and dining room dressed in ruby velvet, aged brass and hand-cut lattice work.",
    narrative: [
      "We rebuilt a heritage narrative in modern skins — every pattern digitised, CNC-cut in our joinery, then finished by hand.",
      "Kitchen extraction, refrigeration and gas were coordinated inside a 3.2m ceiling void with zero visible services in the guest zones.",
      "Delivered from empty shell to opening night in 74 days.",
    ],
  },
  {
    slug: "common-grounds",
    name: "Common Grounds",
    sector: "Restaurants",
    location: "DIFC, JLT",
    client: "Common Grounds",
    scope: "Fit-out & MEP",
    year: "2023",
    image: commongrounds1,
    gallery: [commongrounds2, commongrounds3, commongrounds4, commongrounds6, commongrounds7, commongrounds8],
    summary:
      "A double-height private clubhouse framing the pool through a curtain of travertine, walnut and glass.",
    narrative: [
      "A single continuous travertine plane runs from lobby to poolside, laid on site with 2mm tolerance across 340m².",
      "The sculptural chandelier was built in-house as a bespoke steel armature clad in hand-blown glass.",
      "Smart HVAC zones balance the double-height volume with the intimate lounges without a single visible grille.",
    ],
  },
  {
    slug: "warehouse-gym-difc",
    name: "Warehouse Gym — DIFC",
    sector: "Fitness",
    location: "DIFC, Dubai",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2024",
    image: warehouseGymDIFC1,
    gallery: [warehouseGymDIFC2, warehouseGymDIFC3, warehouseGymDIFC4, warehouseGymDIFC5, warehouseGymDIFC6, warehouseGymDIFC7],
    summary: "A high-performance fitness space in the heart of DIFC.",
    narrative: ["Delivered in DIFC, this project extends Warehouse Gym's signature industrial aesthetic into a new financial district location."],
  },
  {
    slug: "warehouse-gym-khawaneej",
    name: "Warehouse Gym — Khawaneej Mall",
    sector: "Fitness",
    location: "Khawaneej Mall, Dubai",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2024",
    image: warehouseGymKhawaneej1,
    gallery: [warehouseGymKhawaneej2, warehouseGymKhawaneej3, warehouseGymKhawaneej4, warehouseGymKhawaneej5],
    summary: "A raw industrial gym concept at Khawaneej Mall.",
    narrative: ["Another Warehouse Gym location delivered with exposed services, polished concrete and precision-engineered training zones."],
  },
  {
    slug: "warehouse-gym-yas-bay",
    name: "Warehouse Gym — Yas Bay",
    sector: "Fitness",
    location: "Yas Bay, Abu Dhabi",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2024",
    image: warehouseGymYasBay1,
    gallery: [warehouseGymYasBay2, warehouseGymYasBay3, warehouseGymYasBay4, warehouseGymYasBay5, warehouseGymYasBay6, warehouseGymYasBay7, warehouseGymYasBay8, warehouseGymYasBay9, warehouseGymYasBay10, warehouseGymYasBay11, warehouseGymYasBay12, warehouseGymYasBay13],
    summary: "A flagship Warehouse Gym on Abu Dhabi's Yas Bay waterfront.",
    narrative: ["A landmark fitness destination on Yas Bay, combining Warehouse Gym's signature brutalist aesthetic with waterfront views."],
  },
  {
    slug: "natureland-supermarket",
    name: "Natureland Supermarket",
    sector: "Retail",
    location: "Emaar Springs Souk, Dubai",
    client: "Natureland",
    scope: "Fit-out & MEP",
    year: "2024",
    image: natureland1,
    gallery: [natureland2, natureland3],
    summary: "A fresh, organic supermarket fit-out at Emaar Springs Souk.",
    narrative: ["A nature-inspired retail environment designed to showcase organic produce in a warm, welcoming setting."],
  },
  {
    slug: "watch-avenue-difc",
    name: "Watch Avenue — DIFC",
    sector: "Retail",
    location: "DIFC Gate Avenue, Dubai",
    client: "Watch Avenue",
    scope: "Fit-out & Joinery",
    year: "2024",
    image: watchAvenue1,
    gallery: [watchAvenue2, watchAvenue3, watchAvenue4, watchAvenue5, watchAvenue6],
    summary: "A luxury watch retail boutique at DIFC Gate Avenue.",
    narrative: ["A refined retail space for premium timepieces, with custom joinery and controlled lighting to showcase each piece."],
  },
  {
    slug: "du-kiosk",
    name: "DU Kiosk",
    sector: "Retail",
    location: "Abu Dhabi",
    client: "du",
    scope: "Kiosk Fit-out",
    year: "2024",
    image: duKiosk1,
    gallery: [duKiosk2, duKiosk3],
    summary: "A branded telecom kiosk for du in Abu Dhabi.",
    narrative: ["A compact, high-impact retail kiosk delivering du's brand experience in a high-traffic location."],
  },
  {
    slug: "amano-restaurant",
    name: "Amano Restaurant",
    sector: "Restaurants",
    location: "Abu Dhabi",
    client: "Amano Hospitality",
    scope: "Fit-out & MEP",
    year: "2024",
    image: amano1,
    gallery: [amano2, amano3],
    summary: "An Italian restaurant fit-out in Abu Dhabi.",
    narrative: ["A warm, inviting Italian dining destination crafted with natural materials and ambient lighting."],
  },
  {
    slug: "golden-goose",
    name: "Golden Goose",
    sector: "Retail",
    location: "Mall of the Emirates, Dubai",
    client: "Golden Goose",
    scope: "Retail Fit-out",
    year: "2024",
    image: goldenGoose1,
    gallery: [goldenGoose2, goldenGoose3, goldenGoose4, goldenGoose5],
    summary: "A luxury sneaker and apparel boutique at Mall of the Emirates.",
    narrative: ["A brand-perfect retail environment for Golden Goose's signature Italian craftsmanship and laid-back luxury."],
  },
  {
    slug: "al-salam-tower",
    name: "Al Salam Tower",
    sector: "Commercial",
    location: "Dubai Internet City",
    client: "Confidential",
    scope: "Office Fit-out",
    year: "2024",
    image: alSalamTower1,
    gallery: [alSalamTower2, alSalamTower3],
    summary: "A corporate office fit-out at Al Salam Tower, Dubai Internet City.",
    narrative: ["A professional office environment delivered at Al Salam Tower in Dubai Internet City."],
  },
  {
    slug: "octagon-office",
    name: "Octagon Office",
    sector: "Commercial",
    location: "Dubai Internet City",
    client: "Octagon",
    scope: "Office Fit-out",
    year: "2024",
    image: octagonOffice1,
    gallery: [octagonOffice2, octagonOffice3, octagonOffice4, octagonOffice5],
    summary: "A modern office fit-out for Octagon at Dubai Internet City.",
    narrative: ["A contemporary workspace designed to foster collaboration and productivity in Dubai Internet City."],
  },
  {
    slug: "trouvaille-coffee-shop",
    name: "Trouvaille Coffee Shop",
    sector: "Restaurants",
    location: "Circle Mall, JVC, Dubai",
    client: "Trouvaille",
    scope: "Fit-out",
    year: "2024",
    image: trouvaille1,
    gallery: [trouvaille2, trouvaille3, trouvaille4, trouvaille5],
    summary: "A charming coffee shop fit-out at Circle Mall, JVC.",
    narrative: ["A cosy, artisanal coffee destination with warm finishes and an inviting neighbourhood feel."],
  },
  {
    slug: "equities-first-office",
    name: "Equities First Office",
    sector: "Commercial",
    location: "DIFC, Dubai",
    client: "Equities First",
    scope: "Office Fit-out",
    year: "2024",
    image: equitiesFirst1,
    gallery: [equitiesFirst2, equitiesFirst3, equitiesFirst4],
    summary: "A professional office fit-out for Equities First at DIFC.",
    narrative: ["A refined workspace in Dubai's financial district, designed for productivity and professionalism."],
  },
  {
    slug: "baraka-office",
    name: "Baraka Office",
    sector: "Commercial",
    location: "DIFC, Dubai",
    client: "Baraka",
    scope: "Office Fit-out",
    year: "2024",
    image: barakaOffice1,
    gallery: [barakaOffice2, barakaOffice3, barakaOffice4, barakaOffice5, barakaOffice6, barakaOffice7, barakaOffice8, barakaOffice9, barakaOffice10, barakaOffice11],
    summary: "A corporate office fit-out for Baraka at DIFC.",
    narrative: ["A modern, efficient workspace delivered in Dubai International Financial Centre."],
  },
  {
    slug: "flor-restaurant",
    name: "FLOR Restaurant",
    sector: "Restaurants",
    location: "DIFC, Dubai",
    client: "FLOR Hospitality",
    scope: "Fit-out & MEP",
    year: "2024",
    image: flor2,
    gallery: [flor3, flor4, flor6, flor7, flor8, flor9, flor10, flor11, flor12, flor13, flor15, flor16, flor17, flor19, flor20, flor22, flor23],
    summary: "A vibrant restaurant fit-out at DIFC.",
    narrative: ["A distinctive dining destination in DIFC, blending contemporary design with a warm atmosphere."],
  },
  {
    slug: "haldirams-restaurant",
    name: "Haldiram's Restaurant",
    sector: "Restaurants",
    location: "Al Raffa, Dubai",
    client: "Haldiram's",
    scope: "Fit-out & MEP",
    year: "2024",
    image: haldirams4,
    gallery: [haldirams5, haldirams6, haldirams7, haldirams8, haldirams9, haldirams10, haldirams11, haldirams12],
    summary: "A flagship restaurant fit-out for Haldiram's in Al Raffa, Dubai.",
    narrative: ["A spacious Indian dining destination bringing Haldiram's legendary cuisine to a new Dubai location."],
  },
  {
    slug: "warehouse-gym-dubai-science-park",
    name: "Warehouse Gym — Dubai Science Park",
    sector: "Fitness",
    location: "Dubai Science Park",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2024",
    image: warehouseGymDSP1,
    gallery: [warehouseGymDSP2, warehouseGymDSP3, warehouseGymDSP4, warehouseGymDSP5],
    summary: "A Warehouse Gym facility at Dubai Science Park.",
    narrative: ["A new fitness destination in Dubai Science Park, continuing Warehouse Gym's legacy of raw, industrial design."],
  },
  {
    slug: "london-skin-clinic",
    name: "London Skin Clinic",
    sector: "Leisure",
    location: "DIFC, Dubai",
    client: "London Skin Clinic",
    scope: "Clinic Fit-out & MEP",
    year: "2024",
    image: londonSkin1,
    gallery: [londonSkin2, londonSkin3, londonSkin4, londonSkin5, londonSkin7, londonSkin8, londonSkin9, londonSkin10],
    summary: "A premium skincare clinic fit-out at DIFC.",
    narrative: ["A serene, clinical environment designed for patient comfort and advanced skincare treatments."],
  },
  {
    slug: "tbk-restaurant",
    name: "TBK Restaurant",
    sector: "Restaurants",
    location: "Galleria Mall, Jumeira, Dubai",
    client: "TBK Hospitality",
    scope: "Fit-out & MEP",
    year: "2024",
    image: tbk1,
    gallery: [tbk2, tbk3, tbk4, tbk5, tbk6, tbk7, tbk8, tbk9],
    summary: "A restaurant fit-out at Galleria Mall, Jumeira.",
    narrative: ["A dining destination at Galleria Mall, Jumeira, delivered with full fit-out and MEP works."],
  },
  {
    slug: "zara-marina-mall",
    name: "Zara — Marina Mall",
    sector: "Retail",
    location: "Marina Mall, Abu Dhabi",
    client: "Zara / Inditex Group",
    scope: "Retail Fit-out",
    year: "2024",
    image: zaraMarina1,
    gallery: [zaraMarina2, zaraMarina3, zaraMarina4, zaraMarina5],
    summary: "A Zara retail store fit-out at Marina Mall, Abu Dhabi.",
    narrative: ["A flagship Zara store delivered at Marina Mall, Abu Dhabi."],
  },
  {
    slug: "warehouse-gym-business-bay",
    name: "Warehouse Gym — Business Bay",
    sector: "Fitness",
    location: "Business Bay, Dubai",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2024",
    image: warehouseGymBizBay1,
    gallery: [warehouseGymBizBay2, warehouseGymBizBay3, warehouseGymBizBay4, warehouseGymBizBay5, warehouseGymBizBay6, warehouseGymBizBay7],
    summary: "A Warehouse Gym facility in Business Bay, Dubai.",
    narrative: ["A high-energy fitness space delivered in Business Bay, continuing the Warehouse Gym legacy."],
  },
  {
    slug: "warehouse-gym-jumeirah-park",
    name: "Warehouse Gym — Jumeirah Park",
    sector: "Fitness",
    location: "Jumeirah Park, Dubai",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2024",
    image: warehouseGymJumeirahPark1,
    gallery: [warehouseGymJumeirahPark2, warehouseGymJumeirahPark3, warehouseGymJumeirahPark4, warehouseGymJumeirahPark5],
    summary: "A Warehouse Gym facility in Jumeirah Park.",
    narrative: ["A new fitness destination in Jumeirah Park, continuing Warehouse Gym's signature industrial design language."],
  },
  {
    slug: "warehouse-gym-springs-souk",
    name: "Warehouse Gym — Springs Souk",
    sector: "Fitness",
    location: "Springs Souk, Dubai",
    client: "The Warehouse Fitness Center LLC",
    scope: "Fit-out & MEP Works",
    year: "2026",
    image: warehouseGymSpringsSouk1,
    gallery: [warehouseGymSpringsSouk2, warehouseGymSpringsSouk3, warehouseGymSpringsSouk4, warehouseGymSpringsSouk5],
    summary: "A Warehouse Gym facility at Springs Souk, Dubai.",
    narrative: ["A new fitness destination at Springs Souk, bringing Warehouse Gym's signature industrial design to the community."],
  },
];

export const getProjectBySlug = (slug: string) => projects.find((p) => p.slug === slug);
