// One-time script: re-encodes src/assets photos/logos into responsive WebP
// variants, rewrites the import blocks in the files that reference them, and
// emits src/assets/generated/images.ts. Run manually: `node scripts/optimize-images.mjs`.
// Deletes the original source images after a successful re-encode.
import { readFile, writeFile, unlink, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const ASSETS_DIR = path.join(ROOT, "src/assets");
const GENERATED_DIR = path.join(ASSETS_DIR, "generated");
const GENERATED_FILE = path.join(GENERATED_DIR, "images.ts");

const SOURCE_FILES = ["src/lib/projects.ts", "src/routes/index.tsx", "src/routes/about.tsx"];

const PHOTO_WIDTHS = [320, 640, 1280, 1920];
const PHOTO_QUALITY = 78;
const LOGO_WIDTHS = [320, 563];
const LOGO_QUALITY = 90;

const IMPORT_RE = /^import\s+(\w+)\s+from\s+"(@\/assets\/[^"]+)";$/gm;

async function collectImageImports() {
  /** @type {{ varName: string, relImportPath: string, absPath: string, sourceFile: string }[]} */
  const entries = [];
  for (const sourceFile of SOURCE_FILES) {
    const abs = path.join(ROOT, sourceFile);
    const content = await readFile(abs, "utf8");
    for (const match of content.matchAll(IMPORT_RE)) {
      const [, varName, relImportPath] = match;
      const relDiskPath = relImportPath.replace(/^@\//, "src/");
      entries.push({
        varName,
        relImportPath,
        absPath: path.join(ROOT, relDiskPath),
        sourceFile,
      });
    }
  }
  return entries;
}

function isLogo(absPath) {
  return absPath.includes(`${path.sep}assets${path.sep}clients${path.sep}`);
}

async function encodeVariants(entry) {
  const { absPath, varName } = entry;
  const dir = path.dirname(absPath);
  const base = path.basename(absPath, path.extname(absPath));
  const widths = isLogo(absPath) ? LOGO_WIDTHS : PHOTO_WIDTHS;
  const quality = isLogo(absPath) ? LOGO_QUALITY : PHOTO_QUALITY;

  const img = sharp(absPath);
  const meta = await img.metadata();
  const srcWidth = meta.width ?? 0;
  const srcHeight = meta.height ?? 0;

  let useWidths = widths.filter((w) => w <= srcWidth);
  if (useWidths.length === 0) useWidths = [srcWidth];

  const variants = [];
  let originalBytes = 0;
  try {
    const stat = await import("node:fs/promises").then((fs) => fs.stat(absPath));
    originalBytes = stat.size;
  } catch {
    // ignore
  }

  let newBytes = 0;
  for (const w of useWidths) {
    const outPath = path.join(dir, `${base}-${w}.webp`);
    const pipeline = sharp(absPath).resize({
      width: w,
      fit: "inside",
      withoutEnlargement: true,
    });
    const webpOpts = isLogo(absPath) ? { quality, alphaQuality: 100 } : { quality };
    await pipeline.webp(webpOpts).toFile(outPath);
    const outStat = await import("node:fs/promises").then((fs) => fs.stat(outPath));
    newBytes += outStat.size;
    variants.push({ width: w, outPath, importId: `${varName}_${w}` });
  }

  return { entry, variants, srcWidth, srcHeight, originalBytes, newBytes };
}

function toImportSpecifier(absPath) {
  const rel = path.relative(ASSETS_DIR, absPath).split(path.sep).join("/");
  return `@/assets/${rel}`;
}

function buildGeneratedModule(results) {
  const lines = [];
  lines.push("// GENERATED by scripts/optimize-images.mjs — do not edit.");
  lines.push("");
  for (const r of results) {
    for (const v of r.variants) {
      lines.push(`import ${v.importId} from "${toImportSpecifier(v.outPath)}";`);
    }
  }
  lines.push("");
  lines.push("export type ImageSet = { src: string; srcSet: string; width: number; height: number };");
  lines.push("");
  for (const r of results) {
    const srcSet = r.variants.map((v) => `\${${v.importId}} ${v.width}w`).join(", ");
    const largest = r.variants[r.variants.length - 1];
    lines.push(`export const ${r.entry.varName}: ImageSet = {`);
    lines.push(`  src: ${largest.importId},`);
    lines.push(`  srcSet: \`${srcSet}\`,`);
    lines.push(`  width: ${r.srcWidth},`);
    lines.push(`  height: ${r.srcHeight},`);
    lines.push(`};`);
  }
  lines.push("");
  return lines.join("\n");
}

async function rewriteSourceFile(sourceFile, varNames) {
  const abs = path.join(ROOT, sourceFile);
  const content = await readFile(abs, "utf8");
  const lines = content.split("\n");
  const varSet = new Set(varNames);

  const newImport = `import { ${varNames.join(", ")} } from "@/assets/generated/images";`;

  let inserted = false;
  const outLines = [];
  for (const line of lines) {
    const m = line.match(/^import\s+(\w+)\s+from\s+"@\/assets\/[^"]+";$/);
    if (m && varSet.has(m[1])) {
      if (!inserted) {
        outLines.push(newImport);
        inserted = true;
      }
      continue; // drop this line
    }
    outLines.push(line);
  }
  await writeFile(abs, outLines.join("\n"), "utf8");
}

async function main() {
  let entries = await collectImageImports();
  console.log(`Found ${entries.length} tracked image imports across ${SOURCE_FILES.length} files.`);
  const limit = process.env.OPTIMIZE_LIMIT ? Number(process.env.OPTIMIZE_LIMIT) : undefined;
  if (limit) entries = entries.slice(0, limit);

  await mkdir(GENERATED_DIR, { recursive: true });

  const results = [];
  let totalOriginal = 0;
  let totalNew = 0;
  for (const entry of entries) {
    if (!existsSync(entry.absPath)) {
      console.warn(`  ! missing source, skipping: ${entry.absPath}`);
      continue;
    }
    const res = await encodeVariants(entry);
    results.push(res);
    totalOriginal += res.originalBytes;
    totalNew += res.newBytes;
    process.stdout.write(".");
  }
  console.log("");

  // Delete originals only after all encodes succeeded.
  for (const entry of entries) {
    if (existsSync(entry.absPath)) {
      await unlink(entry.absPath);
    }
  }

  const moduleSrc = buildGeneratedModule(results);
  await writeFile(GENERATED_FILE, moduleSrc, "utf8");

  // Group var names by source file for the rewrite step.
  const bySourceFile = new Map();
  for (const entry of entries) {
    if (!bySourceFile.has(entry.sourceFile)) bySourceFile.set(entry.sourceFile, []);
    bySourceFile.get(entry.sourceFile).push(entry.varName);
  }
  for (const [sourceFile, varNames] of bySourceFile) {
    await rewriteSourceFile(sourceFile, varNames);
  }

  console.log("");
  console.log("=== Result ===");
  console.log(`Original: ${(totalOriginal / 1048576).toFixed(1)} MB`);
  console.log(`New:      ${(totalNew / 1048576).toFixed(1)} MB`);
  console.log(`Reduction: ${(100 - (totalNew / totalOriginal) * 100).toFixed(1)}%`);
  console.log(`Generated module: ${path.relative(ROOT, GENERATED_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
