/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogsThingsILearntRouteImport } from './routes/blogs.things-i-learnt'
import { Route as BlogsSixMaterialsSixSectorsRouteImport } from './routes/blogs.six-materials-six-sectors'
import { Route as BlogsSiteSafetyInductionMepRouteImport } from './routes/blogs.site-safety-induction-mep'
import { Route as BlogsSiteSafetyInductionRouteImport } from './routes/blogs.site-safety-induction'
import { Route as BlogsSilentHvacHospitalityRouteImport } from './routes/blogs.silent-hvac-hospitality'
import { Route as BlogsMepInsightsRouteImport } from './routes/blogs.mep-insights'
import { Route as BlogsBookMatchedMarbleBarRouteImport } from './routes/blogs.book-matched-marble-bar'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsThingsILearntRoute = BlogsThingsILearntRouteImport.update({
  id: '/things-i-learnt',
  path: '/things-i-learnt',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsSixMaterialsSixSectorsRoute =
  BlogsSixMaterialsSixSectorsRouteImport.update({
    id: '/six-materials-six-sectors',
    path: '/six-materials-six-sectors',
    getParentRoute: () => BlogsRoute,
  } as any)
const BlogsSiteSafetyInductionMepRoute =
  BlogsSiteSafetyInductionMepRouteImport.update({
    id: '/site-safety-induction-mep',
    path: '/site-safety-induction-mep',
    getParentRoute: () => BlogsRoute,
  } as any)
const BlogsSiteSafetyInductionRoute =
  BlogsSiteSafetyInductionRouteImport.update({
    id: '/site-safety-induction',
    path: '/site-safety-induction',
    getParentRoute: () => BlogsRoute,
  } as any)
const BlogsSilentHvacHospitalityRoute =
  BlogsSilentHvacHospitalityRouteImport.update({
    id: '/silent-hvac-hospitality',
    path: '/silent-hvac-hospitality',
    getParentRoute: () => BlogsRoute,
  } as any)
const BlogsMepInsightsRoute = BlogsMepInsightsRouteImport.update({
  id: '/mep-insights',
  path: '/mep-insights',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsBookMatchedMarbleBarRoute =
  BlogsBookMatchedMarbleBarRouteImport.update({
    id: '/book-matched-marble-bar',
    path: '/book-matched-marble-bar',
    getParentRoute: () => BlogsRoute,
  } as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/book-matched-marble-bar': typeof BlogsBookMatchedMarbleBarRoute
  '/blogs/mep-insights': typeof BlogsMepInsightsRoute
  '/blogs/silent-hvac-hospitality': typeof BlogsSilentHvacHospitalityRoute
  '/blogs/site-safety-induction': typeof BlogsSiteSafetyInductionRoute
  '/blogs/site-safety-induction-mep': typeof BlogsSiteSafetyInductionMepRoute
  '/blogs/six-materials-six-sectors': typeof BlogsSixMaterialsSixSectorsRoute
  '/blogs/things-i-learnt': typeof BlogsThingsILearntRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/book-matched-marble-bar': typeof BlogsBookMatchedMarbleBarRoute
  '/blogs/mep-insights': typeof BlogsMepInsightsRoute
  '/blogs/silent-hvac-hospitality': typeof BlogsSilentHvacHospitalityRoute
  '/blogs/site-safety-induction': typeof BlogsSiteSafetyInductionRoute
  '/blogs/site-safety-induction-mep': typeof BlogsSiteSafetyInductionMepRoute
  '/blogs/six-materials-six-sectors': typeof BlogsSixMaterialsSixSectorsRoute
  '/blogs/things-i-learnt': typeof BlogsThingsILearntRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/book-matched-marble-bar': typeof BlogsBookMatchedMarbleBarRoute
  '/blogs/mep-insights': typeof BlogsMepInsightsRoute
  '/blogs/silent-hvac-hospitality': typeof BlogsSilentHvacHospitalityRoute
  '/blogs/site-safety-induction': typeof BlogsSiteSafetyInductionRoute
  '/blogs/site-safety-induction-mep': typeof BlogsSiteSafetyInductionMepRoute
  '/blogs/six-materials-six-sectors': typeof BlogsSixMaterialsSixSectorsRoute
  '/blogs/things-i-learnt': typeof BlogsThingsILearntRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/services'
    | '/blogs/$slug'
    | '/blogs/book-matched-marble-bar'
    | '/blogs/mep-insights'
    | '/blogs/silent-hvac-hospitality'
    | '/blogs/site-safety-induction'
    | '/blogs/site-safety-induction-mep'
    | '/blogs/six-materials-six-sectors'
    | '/blogs/things-i-learnt'
    | '/projects/$slug'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/services'
    | '/blogs/$slug'
    | '/blogs/book-matched-marble-bar'
    | '/blogs/mep-insights'
    | '/blogs/silent-hvac-hospitality'
    | '/blogs/site-safety-induction'
    | '/blogs/site-safety-induction-mep'
    | '/blogs/six-materials-six-sectors'
    | '/blogs/things-i-learnt'
    | '/projects/$slug'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/services'
    | '/blogs/$slug'
    | '/blogs/book-matched-marble-bar'
    | '/blogs/mep-insights'
    | '/blogs/silent-hvac-hospitality'
    | '/blogs/site-safety-induction'
    | '/blogs/site-safety-induction-mep'
    | '/blogs/six-materials-six-sectors'
    | '/blogs/things-i-learnt'
    | '/projects/$slug'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/things-i-learnt': {
      id: '/blogs/things-i-learnt'
      path: '/things-i-learnt'
      fullPath: '/blogs/things-i-learnt'
      preLoaderRoute: typeof BlogsThingsILearntRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/six-materials-six-sectors': {
      id: '/blogs/six-materials-six-sectors'
      path: '/six-materials-six-sectors'
      fullPath: '/blogs/six-materials-six-sectors'
      preLoaderRoute: typeof BlogsSixMaterialsSixSectorsRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/site-safety-induction-mep': {
      id: '/blogs/site-safety-induction-mep'
      path: '/site-safety-induction-mep'
      fullPath: '/blogs/site-safety-induction-mep'
      preLoaderRoute: typeof BlogsSiteSafetyInductionMepRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/site-safety-induction': {
      id: '/blogs/site-safety-induction'
      path: '/site-safety-induction'
      fullPath: '/blogs/site-safety-induction'
      preLoaderRoute: typeof BlogsSiteSafetyInductionRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/silent-hvac-hospitality': {
      id: '/blogs/silent-hvac-hospitality'
      path: '/silent-hvac-hospitality'
      fullPath: '/blogs/silent-hvac-hospitality'
      preLoaderRoute: typeof BlogsSilentHvacHospitalityRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/mep-insights': {
      id: '/blogs/mep-insights'
      path: '/mep-insights'
      fullPath: '/blogs/mep-insights'
      preLoaderRoute: typeof BlogsMepInsightsRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/book-matched-marble-bar': {
      id: '/blogs/book-matched-marble-bar'
      path: '/book-matched-marble-bar'
      fullPath: '/blogs/book-matched-marble-bar'
      preLoaderRoute: typeof BlogsBookMatchedMarbleBarRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsBookMatchedMarbleBarRoute: typeof BlogsBookMatchedMarbleBarRoute
  BlogsMepInsightsRoute: typeof BlogsMepInsightsRoute
  BlogsSilentHvacHospitalityRoute: typeof BlogsSilentHvacHospitalityRoute
  BlogsSiteSafetyInductionRoute: typeof BlogsSiteSafetyInductionRoute
  BlogsSiteSafetyInductionMepRoute: typeof BlogsSiteSafetyInductionMepRoute
  BlogsSixMaterialsSixSectorsRoute: typeof BlogsSixMaterialsSixSectorsRoute
  BlogsThingsILearntRoute: typeof BlogsThingsILearntRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsBookMatchedMarbleBarRoute: BlogsBookMatchedMarbleBarRoute,
  BlogsMepInsightsRoute: BlogsMepInsightsRoute,
  BlogsSilentHvacHospitalityRoute: BlogsSilentHvacHospitalityRoute,
  BlogsSiteSafetyInductionRoute: BlogsSiteSafetyInductionRoute,
  BlogsSiteSafetyInductionMepRoute: BlogsSiteSafetyInductionMepRoute,
  BlogsSixMaterialsSixSectorsRoute: BlogsSixMaterialsSixSectorsRoute,
  BlogsThingsILearntRoute: BlogsThingsILearntRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
